services:
  mongodb:
    image: mongo:latest
    container_name: auth-rs-mongodb
    # ports:
      # - "27017:27017" # Uncomment if you want to expose MongoDB to the host
    volumes:
      - mongodb_data:/data/db
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME= optional -> has to be included in the backend mongo_uri variable if you use it
      # - MONGO_INITDB_ROOT_PASSWORD= optional -> has to be included in the backend mongo_uri variable if you use it
    networks:
      - auth-rs-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    image: auth-rs-backend:latest
    container_name: auth-rs-backend
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - ROCKET_DATABASES={auth-rs-db={url="mongodb://mongodb:27017"}} # adjust the url="" part if needed
      - SYSTEM_EMAIL=admin@example.com
      - SYSTEM_PASSWORD=admin # Create a strong system user password here
    networks:
      - auth-rs-network
    restart: unless-stopped

  frontend:
    image: auth-rs-frontend:latest
    container_name: auth-rs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_PUBLIC_API_URL=https://oauth.timlohrer.de/api
    networks:
      - auth-rs-network
    restart: unless-stopped

networks:
  auth-rs-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 