[default.databases.auth-rs-db] 
url = "${MONGODB_URI:mongodb://mongodb:27017}"

[default]
address = "0.0.0.0"
port = 8000
limits = { json = "10MiB" }

[release]
address = "0.0.0.0"
port = 8000

[debug]
address = "0.0.0.0"
port = 8000